### ISSUE TITLE
How to push UTM parameters to Google Analytics once saved?

### ISSUE THREAD

**Issue by sneko** [Yesware/last-campaign#3]
Hi @lukebussey ,

It's an old repo I know, but I'm curious:

Once UTM parameters are saved, the user may accept Google Analytics usage let's say, 3 minutes after. At that time, do you know which event to trigger against Google Analytics so it fully understand the UTM parameters?

(I'm on Google Analytics 4, but if you have an example with Universal Analytics I'm fine too)

Thank you,

**Comment by lukebussey** [comment]
Hi Thomas,

Checkout https://github.com/loganbussey/attrify as it's an upgrade to this repo.

Regarding your question about GA, since the utm parameters are on the url, when GA loads, it'll pick up the utm parameters that are on the URL.

**Comment by sneko** [comment]
Thank you for the answer!

In my case and due to some privacy compliance, the user has a "popover" that asks for his consent for tracking... The user can navigate across the website during a few minutes before accepting (so the URL after a few minutes no longer contains UTM parameters).

Once he accepts it will start adding the Google script and start tracking each pageview...

That's why I need to find a way once loaded to say to Google "hey, the original UTM parameters were X,Y,Z" :)

But maybe I should look at a library/helper that stores UTM parameters in `sessionStorage` (so it's scope to the tab, and not across all tabs/windows due to cookies). What do you think?

**Comment by lukebussey** [comment]
I'm not familiar with GA4, but when it loads, you could append the utm parameters that are saved in the session cookie to the page url that is sent to Google. E.g.

```
gtag('config', 'MEASUREMENT_ID', {
  page_title : 'My Profile',
  page_location: 'https://example.com/me' // The full URL is required.
});
```

https://support.google.com/analytics/answer/11403294?hl=en

**Comment by sneko** [comment]
Thanks for pointing this to me and answering 👍 

To fulfill all my needs I ended creating a new package https://github.com/sneko/utm-synapse that is based on `sessionStorage` and allow improving the URL browser display.
